name: Deploy to development server

on:
  push:
    branches: [ develop, experimental ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Tracking.sln
    - name: Build
      run: dotnet build --no-restore Tracking.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Tracking.sln
      
    - name: Publish migrator
      run: dotnet publish --self-contained -o publish/migrator/ -f net5.0 -r linux-x64 src/Tracking.Migration.Runner/Tracking.Migration.Runner.csproj 
    - name: Publish the host
      run: dotnet publish --self-contained -o publish/host/ -f net5.0 -r linux-x64 src/Tracking.Host/Tracking.Host.csproj 
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'host'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: Copying the migrator
      run: | 
          rm publish/migrator/appsettings.json
          rsync -avz ./publish/migrator/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/tracking/migrator/
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:./home/tracking/migrator/Tracking.Migration.Runner
